name: Build RSS Feed

on:
  schedule:
    # UPDATED: Runs every 30 mins between 5 AM and 10 PM Pacific Time
    - cron: '*/90 12-23,0-4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper to generate feed
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "RSS Bot"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feed" && git push)
