# .github/workflows/main.yml
name: Build RSS Feed

on:
  schedule:
    # Runs every 6 hours. You can change this schedule.
    - cron: '0 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

     permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper to generate feed
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "RSS Bot"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feed" && git push)
